image:
  file: .gitpod.Dockerfile

tasks:
  - before: dotnet restore
  - init: npm install && npm run build compiler

vscode:
  extensions:
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - Ionide.Ionide-fsharp@4.5.0:0qxXuhq6eO066etkNQrKCQ==
