name: Bundle and deploy to tecent

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      
    - name: Install dependencies
      run: |
        dotnet tool install fake-cli -g
        dotnet tool install paket -g
        npm install yarn -g
           
    - name: Bundle
      run: fake build -t Bundle
