name: Bundle and deploy to Tencent

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install yarn -g
           
    - name: Bundle
      run: dotnet fsi ./build.fsx -t Bundle

    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/Tetris/Tetris/deploy/publish/
        remote: ${{ secrets.REMOTE_TARGET }}/TetrisDeploy
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PWD }}
        
    - name: Run SSH command
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PWD }}
        script: |
          echo Stop website
          sudo pkill -f ${{ secrets.REMOTE_LOCALHOST }}:${{ secrets.REMOTE_PORT }}
          echo Copy files
          cp -r -f  ${{ secrets.REMOTE_TARGET }}/TetrisDeploy/* ${{ secrets.REMOTE_TARGET }}/Tetris
          echo Start website
          cd ${{ secrets.REMOTE_TARGET }}/Tetris
          sudo nohup dotnet Tetris.Server.WebApi.dll --urls http://${{ secrets.REMOTE_LOCALHOST }}:${{ secrets.REMOTE_PORT }} > Tetris.out 2>&1 &
        
    
