name: Bundle and deploy to Tencent

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      
    - name: Install dependencies
      run: |
        dotnet tool install fake-cli -g
        dotnet tool install paket -g
        npm install yarn -g
           
    - name: Bundle
      run: fake build -t Bundle

    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: /home/runner/work/Tetris/Tetris/deploy/publish/
        remote: ${{ secrets.REMOTE_TARGET }}/TetrisDeploy
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PWD }}
        
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PWD }}
        command: |
          echo Stop website
          sudo pkill -f 172.17.0.14:86
          echo Copy files
          cp -r -f  ${{ secrets.REMOTE_TARGET }}/TetrisDeploy/* ${{ secrets.REMOTE_TARGET }}/Tetris
          echo Start website
          cd ${{ secrets.REMOTE_TARGET }}/Tetris
          sudo nohup dotnet Tetris.Server.WebApi.dll --urls http://172.17.0.14:86 > Tetris.out 2>&1 &
        
    
